name: Frontend Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  frontend_cd_pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ "16" ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: npm ci
      - name: Build production website
        run: npm run build --if-present

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Copy files to the production website with the AWS CLI
        run: |
          aws s3 sync ./build s3://s3-website-bucket-6c58d81
